<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUvl4Uh7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUvl4Uh7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUvl4Uh7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUvl4Uh7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUvl4Uh7\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uvl4Uh7',
    'container.build_id' => 'a01ad044',
    'container.build_time' => 1680989959,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUvl4Uh7');
